server:
  port: 28889

okhttp4:
  enabled: true
  connectTimeout: 2000
  readTimeout: 3000
  writeTimeout: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiaoyi?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: root
    password: mysqlroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 相关
  jpa:
    hibernate:
      ddl-auto: create   #ddl-auto:设为 create 表示每次都重新建表
    show-sql: true

logging:
  level:
    pro:
      jiaoyi: DEBUG