server:
  port: 28889

okhttp4:
  enabled: true
  connectTimeout: 2000
  readTimeout: 3000
  writeTimeout: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiaoyi?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&useSSL=true
    username: root
#    password: mysqlroot
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 相关
  jpa:
    hibernate:
      ddl-auto: update   #ddl-auto:设为 create 表示每次都重新建表
    show-sql: false

logging:
  level:
    pro:
      jiaoyi: INFO

project:
  dir: /Users/dwd/dev/GitHub/jiaoyi