server:
  port: 28890

okhttp4:
  enabled: true
  connectTimeout: 2000
  readTimeout: 3000
  writeTimeout: 3000

logging:
  level:
    pro:
      jiaoyi: DEBUG

spring:
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mysql://localhost:3306/jiaoyi?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: root
    #    password: mysqlroot
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 相关
  jpa:
    hibernate:
      ddl-auto: update   #ddl-auto:设为 create 表示每次都重新建表
    show-sql: false

project:
  dir: /Users/dwd/dev/GitHub/jiaoyi
dailyJob:
  enable: true
#  enable: false