server:
  port: 8890

okhttp4:
  enabled: true
  connectTimeout: 2000
  readTimeout: 3000
  writeTimeout: 3000

logging:
  level:
    pro:
      jiaoyi: DEBUG

spring:
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html