server:
  port: 8888

okhttp4:
  enabled: true
  connectTimeout: 2000
  readTimeout: 3000
  writeTimeout: 3000

tushare:
  token: 1176f5f365d3584c2dbeced67b4bdc7f4385a97c0f2c6f9b31012966
  baseUrl: http://api.tushare.pro

logging:
  level:
    pro:
      jiaoyi: DEBUG