server:
  port: 8888

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: DEBUG

okhttp4:
  enabled: true
  connectTimeout: 3000
  readTimeout: 3000
  writeTimeout: 3000