server:
  port: 20002
  servlet:
    context-path: /search

okhttp4:
  enabled: true
  connectTimeout: 2000
  readTimeout: 3000
  writeTimeout: 3000


baidu:
  app:
    text:
      api_key: eFh22ROwlfj06CwK5fLeG8Cw
      secret_key: RXC1Z7ZNvAkRFMInN0FqyBhQIgFieBsz

jieba:
  url: http://127.0.0.1:20001/jieba

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/jiaoyi?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
#    username: root
#    #    password: mysqlroot
#    password: 12345678
#
    url: jdbc:mysql://rm-cn-uax3cavow000diqo.rwlb.rds.aliyuncs.com:3306/jiaoyi?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: aliroot
    password: Mysql@aliroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 相关
  jpa:
    hibernate:
      ddl-auto: update   #ddl-auto:设为 create 表示每次都重新建表
    show-sql: false