server:
  port: 20002
  servlet:
    context-path: /search

okhttp4:
  enabled: true
  connectTimeout: 2000
  readTimeout: 3000
  writeTimeout: 3000


baidu:
  app:
    text:
      api_key: eFh22ROwlfj06CwK5fLeG8Cw
      secret_key: RXC1Z7ZNvAkRFMInN0FqyBhQIgFieBsz

jieba:
  url: http://127.0.0.1:20001/jieba